- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20231130"
  highlight_links:
    - title: Confronto EDR
      url: https://attackevals.mitre-engenuity.org/results/enterprise?vendor=crowdstrike&vendor=paloaltonetworks&vendor=sentinelone&evaluation=turla&scenario=1
  id: 1
  length: 28
  published: true
  summary: Le organizzazioni si sono dotate di diverse soluzioni di sicurezza, e tali soluzioni hanno generalmente vita propria. Riflessioni su soluzioni silos, possibili integrazioni e rischi.
  tags: []
  title: Orchestrazione di sistemi di sicurezza (parte 1)
  url: https://www.spreaker.com/episode/0x1-orchestrazione-di-sistemi-di-sicurezza-parte-1--57864841
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20231201"
  highlight_links:
    - title: Confronto EDR
      url: https://attackevals.mitre-engenuity.org/results/enterprise?vendor=crowdstrike&vendor=paloaltonetworks&vendor=sentinelone&evaluation=turla&scenario=1
  id: 2
  length: 23
  published: true
  summary: "(continua dall'episodio precedente)\n\nLe organizzazioni si sono dotate di diverse soluzioni di sicurezza, e tali soluzioni hanno generalmente vita propria. Riflessioni su soluzioni silos, possibili integrazioni e rischi."
  tags: []
  title: Orchestrazione di sistemi di sicurezza (parte 2)
  url: https://www.spreaker.com/episode/0x2-orchestrazione-di-sistemi-di-sicurezza-parte-2--57864845
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20231221"
  highlight_links:
    - title: Confronto EDR
      url: https://attackevals.mitre-engenuity.org/results/enterprise?vendor=crowdstrike&vendor=paloaltonetworks&vendor=sentinelone&evaluation=turla&scenario=1
  id: 3
  length: 26
  published: true
  summary: Scegliere, gestire, utilizzare una soluzione di Endpoint Detection and Response o EDR.
  tags: []
  title: "EDR: scegliere, gestire, utilizzare (parte 1)"
  url: https://www.spreaker.com/episode/0x3-edr-scegliere-gestire-utilizzare-parte-1--58085880
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20231222"
  highlight_links:
    - title: Confronto EDR
      url: https://attackevals.mitre-engenuity.org/results/enterprise?vendor=crowdstrike&vendor=paloaltonetworks&vendor=sentinelone&evaluation=turla&scenario=1
  id: 4
  length: 30
  published: true
  summary: "(continua dall'episodio precedente)\n\nScegliere, gestire, utilizzare una soluzione di Endpoint Detection and Response o EDR."
  tags: []
  title: "EDR: scegliere, gestire, utilizzare (parte 2)"
  url: https://www.spreaker.com/episode/0x4-edr-scegliere-gestire-utilizzare-parte-2--58085883
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240104"
  highlight_links:
    - title: EDR Evasion Primer
      url: https://conference.hitb.org/hitbsecconf2022sin/materials/D1T1%20-%20EDR%20Evasion%20Primer%20for%20Red%20Teamers%20-%20Karsten%20Nohl%20&%20Jorge%20Gimenez.pdf
    - title: Cybersecurity Podcast
      url: https://open.spotify.com/show/3GuETTlTQC1HVClDwo6GPk
    - title: TIBER
      url: https://www.ecb.europa.eu/paym/cyber-resilience/tiber-eu/html/index.en.html
  id: 5
  length: 46
  published: true
  summary: Continua la riflessione sul mondo EDR iniziata nelle due puntati precedenti che porta inevitabilmente a parlare di XDR.
  tags: []
  title: "Da EDR a XDR: scegliere, gestire, utilizzare (parte 1)"
  url: https://www.spreaker.com/episode/0x5-da-edr-a-xdr-scegliere-gestire-utilizzare-parte-1--58197896
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240105"
  highlight_links:
    - title: EDR Evasion Primer
      url: https://conference.hitb.org/hitbsecconf2022sin/materials/D1T1%20-%20EDR%20Evasion%20Primer%20for%20Red%20Teamers%20-%20Karsten%20Nohl%20&%20Jorge%20Gimenez.pdf
    - title: Cybersecurity Podcast
      url: https://open.spotify.com/show/3GuETTlTQC1HVClDwo6GPk
    - title: TIBER
      url: https://www.ecb.europa.eu/paym/cyber-resilience/tiber-eu/html/index.en.html
  id: 6
  length: 33
  published: true
  summary: "(continua dall'episodio precedente)\n\nContinua la riflessione sul mondo EDR iniziata nelle due puntati precedenti che porta inevitabilmente a parlare di XDR."
  tags: []
  title: "Da EDR a XDR: scegliere, gestire, utilizzare (parte 2)"
  url: https://www.spreaker.com/episode/0x6-da-edr-a-xdr-scegliere-gestire-utilizzare-parte-2--58197897
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240202"
  highlight_links: []
  id: 7
  length: 30
  published: true
  summary: Apriamo il tema della sicurezza negli ambienti ICS/OT. Spunti e riflessioni aperte su come approcciare un mondo che ricorda l'IT di 25 anni fa.
  tags: []
  title: Sicurezza negli impianti OT (parte 1)
  url: https://www.spreaker.com/episode/0x7-sicurezza-negli-impianti-ot-parte-1--58542931
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240203"
  highlight_links: []
  id: 8
  length: 42
  published: true
  summary: "(continua dall'episodio precedente)\n\nApriamo il tema della sicurezza negli ambienti ICS/OT. Spunti e riflessioni aperte su come approcciare un mondo che ricorda l'IT di 25 anni fa."
  tags: []
  title: Sicurezza negli impianti OT (parte 2)
  url: https://www.spreaker.com/episode/0x8-sicurezza-negli-impianti-ot-parte-2--585429692
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240221"
  highlight_links: []
  id: 9
  length: 43
  published: true
  summary: "Attacco con prossimità fisica: cosa possiamo vedere con un rouge device opportunamente posizionato? Quanto rumore facciamo? E sopratutto: come possiamo individuare dispositivi malevoli?"
  tags: []
  title: "Attacco di prossimità con rogue device e strategie di difesa (parte 1)"
  url: https://www.spreaker.com/episode/0x9-attacco-di-prossimita-con-rogue-device-e-strategie-di-difesa-parte-1--58766770
- authors:
    - Alice Mini
    - Andrea Dainese
  date: "20240222"
  highlight_links: []
  id: 10
  length: 22
  published: true
  summary: "(continua dall'episodio precedente)\n\nAttacco con prossimità fisica: cosa possiamo vedere con un rouge device opportunamente posizionato? Quanto rumore facciamo? E sopratutto: come possiamo individuare dispositivi malevoli?"
  tags: []
  title: "Attacco di prossimità con rogue device e strategie di difesa (parte 2)"
  url: https://www.spreaker.com/episode/0xa-attacco-di-prossimita-con-rogue-device-e-strategie-di-difesa-parte-2--58766863
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240608"
  highlight_links: []
  id: 11
  length: 50
  published: true
  summary: "Nella puntata precedente abbiamo parlato di attacchi di prossimità e abbiamo volontariamente omesso le soluzioni basate su 802.1x. Affrontiamo l'argomento alla luce degli esperimenti fatti, mettendo in luce pregi e ombre delle soluzioni NAC. La riflessione parte dal rischio e dalla percezione che determinate soluzioni risolvano un problema. La discussione di sposta quindi su come possiamo disegnare le reti campus per far fronte agli scenari di attacco."
  tags: []
  title: "802.1x bypass: riflessioni sugli impatti e sgli approcci per ridurre il rischio"
  url: https://www.spreaker.com/episode/0xb-802-1x-bypass-riflessioni-sugli-impatti-e-sgli-approcci-per-ridurre-il-rischio--60187964
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20240916"
  highlight_links: []
  id: 12
  length: 64
  published: true
  summary: Mettendoci nei panni di un CISO appena insediatosi presso una nuova azienda, riflettiamo sui temi da affrontare. In questa prima puntata facciamo un brainstorming per elencare i temi che approfondiremo nelle puntate seguenti.
  tags: []
  title: Ripartiamo dall'inizio
  url: https://www.spreaker.com/episode/0xc-ripartiamo-dall-inizio--61809624
- authors:
    - Alice Mini
    - Andrea Dainese
  date: "20240929"
  highlight_links: []
  id: 13
  length: 27
  published: true
  summary: Con Alice Mini prendiamo spunto da un account di posta compromesso per riflettere sugli impatti, sul processo di Awareness e su come migliorare i processi aziendali.
  tags: []
  title: "[EXT] Account di posta compromesso"
  url: https://www.spreaker.com/episode/0xd-ext-account-di-posta-compromesso--62152485
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20241016"
  highlight_links: []
  id: 14
  length: 33
  published: true
  summary: "All'evento NTS Passion tenutosi a Verona, abbiamo parlato delle più comuni debolezze che rendono possibile effettuare attacchi con successo alle organizzazioni."
  tags: []
  title: "[PUB] Accesso non consentito (ma possibile)"
  url: https://www.spreaker.com/episode/0xe-pub-accesso-non-consentito-ma-possibile--62386146
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20241202"
  highlight_links: []
  id: 15
  length: 47
  published: true
  summary: "Torniamo a metterci i panni di un un CISO appena insediatorsi presso una unova  azienda (vedi 0xc) e affrontiamo il tema della compliance. In questa puntata vediamo come e perchè usare le certificazioni a nostro vantaggio."
  tags: []
  title: La compliance normativa come vantaggio
  url: https://www.spreaker.com/episode/0xf-la-compliance-normativa-come-vantaggio--63071211
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20241212"
  highlight_links: []
  id: 16
  length: 25
  published: true
  summary: "Con Alice Mini partiamo da due attacchi DDoS reali per riflettere su mitigazione, strategie di difesa, consapevolezza.\n\nIl podcast è stato registrato \"on the road\" per non perdere l'ispirazione del momento."
  tags: []
  title: "[EXT] Attacchi DDoS e strategie di sopravvivenza"
  url: https://www.spreaker.com/episode/0x10-ext-attacchi-ddos-e-strategie-di-sopravvivenza--63286769
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20241216"
  highlight_links: []
  id: 17
  length: 59
  published: true
  summary: "Sempre nei panni di un CISO discutiamo di documentazione, tecnica e non: approcci e strumenti per fare ordine tra le informazioni aziendali."
  tags: []
  title: Documentazione tecnica
  url: https://www.spreaker.com/episode/0x11-documentazione-tecnica--63302501
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20241230"
  highlight_links: []
  id: 18
  length: 39
  published: true
  summary: La rete vista dall'IT manager e dal CISO. Una prima riflessione sulle implementazioni, sulla sicurezza, sull'approccio Zero Trust... Argomento troppo ampio per esaurirlo in una sola puntata.
  tags: []
  title: Riflessioni sulla rete (design, sicurezza, approccio)
  url: https://www.spreaker.com/episode/0x12-riflessioni-sulla-rete-design-sicurezza-approccio--63459252
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250113"
  highlight_links: []
  id: 19
  length: 46
  published: true
  summary: Continuano le riflessioni sulla rete e ci focalizziamo sul datacenter. In particolare riflettiamo sul design, su concetti di microsegmentazione, sulle reti storage e converged.
  tags: []
  title: Approfondimento sulle reti datacenter
  url: https://www.spreaker.com/episode/0x13-approfondimento-sulle-reti-datacenter--63459253
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250128"
  highlight_links: []
  id: 20
  length: 37
  published: true
  summary: "Una decina scarsa di anni fa nasce da una chiacchierata l'idea del CISO as a Service (CISOaaS), poi ribbattezzato vCISO. Ripercorriamo in due puntate come è nata l'idea, come è diventata una linea di business, e facciamo alcune considerazioni su CISO e vCISO, due possibilità che non sono in contrapposizione."
  tags: []
  title: CISO, vCISO, CISOaaS, un'idea nata molti anni fa (parte 1)
  url: https://www.spreaker.com/episode/0x14-ciso-vciso-cisoaas-un-idea-nata-molti-anni-fa-parte-1--63934820
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250210"
  highlight_links: []
  id: 21
  length: 40
  published: true
  summary: "In questa puntata si approfondiscono i vantaggi e gli svantaggi nell'affidarsi a figure esterne rispetto a risorse interne all'azienda. Si esplorano due scenari principali: da un lato, i consulenti o collaboratori esterni portano una visione più ampia e competenze diversificate; dall'altro, le figure interne garantiscono una conoscenza approfondita del settore e della realtà aziendale. Una riflessione utile per chi deve decidere come strutturare il proprio team e bilanciare innovazione e continuità."
  tags: []
  title: CISO, vCISO, CISOaaS, un'idea nata molti anni fa (parte 2)
  url: https://www.spreaker.com/episode/0x15-ciso-vciso-cisoaas-un-idea-nata-molti-anni-fa-parte-2--63934822
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250517"
  highlight_links: []
  id: 22
  length: 33
  published: true
  summary: In questa puntata di Infosec Unplugged, Andrea Dainese e Rocco Sicilia affrontano i temi della sicurezza industriale e delle tecnologie operative (OT). Partendo da un evento dedicato al settore, condividono esperienze e riflessioni sui principali problemi che le aziende si trovano ad affrontare quando approcciano la cybersecurity in contesti industriali, con particolare attenzione al ruolo di CIO e CISO nella gestione dei rischi.
  tags:
    - OT Security
    - NTS
  title: Sicurezza ICS/OT (da un evento NTS)
  url: https://www.spreaker.com/episode/0x16-sicurezza-ics-ot-da-un-evento-nts--66128035
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250602"
  highlight_links:
    - title: Evento NTS - Sicurezza ICS/OT
      url: https://www.nts.eu/it/event/sicurezza-ics-ot/?utm_campaign=personalbranding
  id: 23
  length: 52
  published: true
  summary: In questa puntata di Infosec Unplugged, Andrea Dainese e Rocco Sicilia introducono il vasto tema della Threat Intelligence, ponendo le basi per comprenderne i principi e le applicazioni pratiche. Partendo dalla raccolta e analisi del dato, discutono come sistemi come EDR e XDR si siano evoluti, quali siano le loro funzionalità principali e in che modo contribuiscano a migliorare la sicurezza informatica aziendale. Un episodio che getta le fondamenta per affrontare con maggiore consapevolezza i meccanismi della difesa cyber.
  tags:
    - Threat Intelligence
    - EDR
    - XDR
  title: Threat Intelligence (parte 1)
  url: https://www.spreaker.com/episode/0x17-threat-intelligence-parte-1--66128443
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250825"
  highlight_links: []
  id: 24
  length: 46
  published: true
  summary: In questa puntata di Info Sec. Unplugged, Andrea Dainese e Rocco Sicilia tornano dietro ai microfoni dopo la pausa estiva per approfondire i temi legati alla sicurezza informatica. Partendo dal confronto tra EDR e SIEM, i due discutono di come queste tecnologie si integrino e si completino a vicenda, sfatando l'idea che una possa sostituire l'altra. La conversazione si concentra su come le organizzazioni possano fare un passo evolutivo nell'uso di queste piattaforme, passando da strumenti puramente reattivi a soluzioni che abilitano una difesa proattiva e contributiva.
  tags:
    - EDR
    - SIEM
    - Threat Detection
    - Incident Response
  title: Threat Intelligence (parte 2)
  url: https://www.spreaker.com/episode/0x18-threat-intelligence-parte-2--67368804
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250908"
  highlight_links:
    - title: Blog post di approfondimento
      url: https://roccosicilia.com/2025/09/08/info-sec-unplugged-18-threat-int-3a-parte/?utm_source=website
    - title: Highlight e dettagli sugli indicatori discussi (video)
      url: https://www.youtube.com/watch?v=3LJb2OtQf28?utm_source=website
  id: 25
  length: 58
  published: true
  summary: In questa puntata di Info Sec. Unplugged, Andrea Dainese e Rocco Sicilia esplorano il tema dell'analisi degli incidenti di sicurezza con un focus particolare sul lavoro del threat analyst, che studia il comportamento degli attori malevoli per supportare attività di detection e prevention. Viene inoltre approfondita la stretta relazione tra il mondo della threat intelligence e quello della offensive security, mostrando come entrambi si concentrino sul modus operandi degli attacchi e sugli artefatti utilizzati dai threat actor. La puntata introduce anche un esempio pratico di analisi di un piccolo incidente di sicurezza, accompagnato da un post descrittivo e un video highlight, per rendere più accessibili i dettagli tecnici trattati.
  tags:
    - Threat Intelligence
    - Incident Response
    - Security Incident
    - Offensive Security
    - Detection
    - Prevention
    - Cyber Attack
    - Command and Control
    - IOC
    - Adversary Simulation
    - Security Analyst
    - Phishing
  title: Threat Intelligence (parte 3)
  url: https://www.spreaker.com/episode/0x19-threat-intelligence-parte-3--67664347
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20250922"
  highlight_links:
    - title: Highlight (video)
      url: https://youtu.be/1gieddeZxWw
    - title: Blog post di approfondimento
      url: https://roccosicilia.com/2025/09/22/info-sec-unplugged-1a-dr-e-cyber-recovery-parte-1/?utm_source=website
  id: 26
  length: 42
  published: true
  summary: In questa puntata di Info Sec. Unplugged si esplora il tema (spesso sottovalutato) del disaster recovery in risposta agli attacchi informatici. Si analizzano i limiti delle strategie tradizionali, l'importanza della separazione tra ambienti, le implicazioni dei backup immutabili e delle golden image, e come una corretta automazione e gestione dei privilegi possano fare la differenza tra la resilienza e la perdita totale dei dati. Il racconto si arricchisce di esperienze reali e casi pratici tipici delle aziende italiane, con un occhio alle nuove sfide aperte dal GDPR e dalla digitalizzazione delle infrastrutture.
  tags:
    - Disaster Recovery
    - Ransomware
    - Backup
    - Golden Image
    - Tabletop Exercise
    - Business Impact Analysis
    - GDPR
    - Automazione
    - Privilege Escalation
    - Red Teaming
    - Cloud
    - Hypervisor
    - Data Retention
  title: DR e Cyber recovery (parte 1)
  url: https://www.spreaker.com/episode/0x1a-dr-e-cyber-recovery-parte-1--67835796
- authors:
    - Andrea Dainese
    - Rocco Sicilia
  date: "20251006"
  highlight_links: []
  id: 27
  length: 56
  published: false
  summary: Questa puntata di Info Sec. Unplugged è dedicata al tema del disaster recovery e alla sua evoluzione nell'era degli attacchi Cyber. Andrea Dainese e Rocco Sicilia accompagnano l'ascoltatore nella progettazione di processi e tecnologie per il DR, evidenziando le differenze tra esigenze di business e scelte tecniche, le sfide offerte dalle nuove normative e l'importanza della resilienza. Una chiacchierata pragmatica e divulgativa, ricca di aneddoti e consigli pratici per chi si occupa di sicurezza informatica e gestione delle infrastrutture IT.
  tags:
    - Disaster Recovery
    - Business Impact Analysis
    - RTO
    - RPO
    - Cloud
    - DORA
    - Supply Chain
    - Automazione
    - Ransomware
  title: DR e Cyber recovery (parte 2)
  url: https://www.spreaker.com/episode/0x1b-dr-e-cyber-recovery-parte-2--67835961
